name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build Docker image
        run: docker build -t drjseifu/enku-backend .
      
      - name: Publish Docker image
        run: docker push drjseifu/enku-backend:latest
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Hulu AWS Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PIXEL_ADDIS_AWS_HOST }}
          username: ${{ secrets.PIXEL_ADDIS_AWS_USER }}
          key: ${{ secrets.PIXEL_ADDIS_SSH_PRIVATE_KEY }}
          script: |
            sudo docker-compose down --remove-orphans
            sudo docker rmi -f drjseifu/enku-backend:latest
            sudo docker-compose up -d
